nome = input('Digite seu nome: ')
print('É um prazer te conhecer, {}!'.format(nome))
n1 = int(input('Digite um valor: '))
n2 = int(input('Digite outro valor: '))
print(f'A soma entre {n1} e {n2} é igual a {n1+n2}!')
