print('-=' * 12)
print('ANALISADOR DE TRIÂNGULOS')
print('-=' * 12)
r1 = float(input('Informe o primeiro segmento: '))
r2 = float(input('Informe o segundo segmento: '))
r3 = float(input('print('-=' * 12)
print('ANALISADOR DE TRIÂNGULOS')
print('-=' * 12)
r1 = float(input('Informe o primeiro segmento: '))
r2 = float(input('Informe o segundo segmento: '))
r3 = float(input('Informe o terceiro segmento: '))
print(f'Os segmentos acima PODEM FORMAR um triângulo.' if (r1 + r2) > r3 and (r1 + r3) > r2 and (r2 + r3) > r1
      else 'Os segmentos acima NÃO PODEM FORMAR um triângulo.')
